name: "Get Key Vault Secret"
description: "Get Secret from Azure Key Vault and masking as a secret"

inputs:
  azure_credentials:
    description: "Azure AD credentials"
    required: true
  vault_name:
    description: "KeyVault name"
    required: true
  secret_name:
    description: "Secret name"
    required: true

outputs:
  secret:
    description: "KeyVault Secret"
    value: "${{ steps.secret.outputs.result }}"

runs:
  using: "composite"
  steps:
    - name: Set secret filename
      run: |
        echo "mildronize_action_az_cli_keyvault_secret=secret-$(date +%s).txt" >> $GITHUB_ENV
      shell: bash

    - uses: azure/login@v1
      with:
        creds: ${{ inputs.azure_credentials }}

    - name: Get Secret from Azure KeyVault
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az keyvault secret show \
          --vault-name ${{ inputs.vault_name }} \
          --name ${{ inputs.secret_name }} \
          --output json > ${{ env.mildronize_action_az_cli_keyvault_secret }}

    - name: Get the value from Secret JSON
      uses: thaitype/actions-yq-secret@hotfix/create-permission-denied # TODO: test branch, when prodution must change to tag (e.g. `v1`)
      id: secret
      with:
        cmd: yq '.value' ${{ env.mildronize_action_az_cli_keyvault_secret }}
        sensitive: true

    - name: Clean tmp files
      run: |
        rm -f ${{ env.mildronize_action_az_cli_keyvault_secret }}
      shell: bash